export const restApiConfig = {
  host:'http://localhost:8080/',
  logIn:'api/v1/auth/login',
  countries: 'api/v1/country/list',
  cpvs: 'api/v1/cpv/list',
  typesOfTender: 'api/v1/type_of_tender/list',
  currencies: 'api/v1/currency/list',
  newTender: 'api/v1/tenders/create',
  newOffer: 'api/v1/offers',
  uploadFile: 'api/v1/files/upload',
  presignedUrl: 'api/v1/document/location',
  total: 'api/v1/total',
  tendersList: 'api/v1/tender/list',
  tenderDetails: 'api/v1/tender/details',
  offerDetails: 'api/v1/offers/details',
  offersList: 'api/v1/offers/list',
  awardDecision: 'api/v1/offers/decision/award',
  rejectDecision: 'api/v1/offers/decision/reject',
  decision: 'api/v1/offers/decision',
};
